# Generated by Django 2.1.7 on 2019-05-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt', models.CharField(max_length=200)),
            ],
        ),
    ]
